services:
  marathon-pacer:
    build: .
    ports:
      - "80:5000" # Use port 80 for EC2 (default)
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: marathon-pacer
