services:
  marathon-pacer:
    build: .
    container_name: marathon-pacer
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
  certbot:
    build: ./certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    depends_on:
      - nginx

volumes:
  certbot-etc:
  certbot-var:
